WorldSource for the Worldgen
feather-rs/feather pull request #415
Opened 2021-04-18 17:46 UTC by michidk

# WorldSource for the Worldgen

## Status

- [x] Ready 

## Description

I implemented a WorldSource for the worldgen

## Related issues

_Leave empty if none_

## Checklist

- [x] Ran `cargo fmt`, `cargo clippy`, `cargo build --release` and `cargo test` and fixed any generated errors!
- [x] Removed unnecessary commented out code
- [x] Used specific traces (if you trace actions please specify the cause i.e. the player)

2021-04-18 19:21 UTC, Schuwi commented on feather/common/src/world_source/world_gen.rs
> +// World source that uses the world generator crate
This should be a doc comment (`///`)

2021-04-18 19:26 UTC, Schuwi commented on feather/worldgen/src/lib.rs
> +            for z in 0..4 {
This... doesn't seem right but I don't claim to 100% understand what's going on. Why is this change necessary?

2021-04-18 19:30 UTC, Schuwi commented on feather/worldgen/src/finishers/clumped.rs
> +                            if chunk.biomes().get(pos_x / 4, 0, pos_z / 4) != biome {
Same here, why is this change necessary?

2021-04-18 20:02 UTC, Schuwi commented
The problem seems to be that with 1.16 Minecraft switched to using a 3D grid for biomes and simultaneously changed the resultion to 4x4x4 biome cells per chunk section instead of the 16x16 (biome per block column) resolution as before.
See here: https://github.com/feather-rs/feather/blob/679bc6e8c988425ef448004ed806120190c62164/feather/base/src/chunk/biome_store.rs#L11-L20

While `feather-base` is updated to the new system, `feather-worldgen` doesn't seem to be updated yet:
https://github.com/feather-rs/feather/blob/0f6f217af81d753d7b697b80a8de206eb9cf5407/feather/worldgen/src/lib.rs#L324-L330

2021-04-18 20:03 UTC, Schuwi requested changes
The problem seems to be that with 1.16 Minecraft switched to using a 3D grid for biomes and simultaneously changed the resultion to 4x4x4 biome cells per chunk section instead of the 16x16 (biome per block column) resolution as before.
See here: https://github.com/feather-rs/feather/blob/679bc6e8c988425ef448004ed806120190c62164/feather/base/src/chunk/biome_store.rs#L11-L20

While `feather-base` is updated to the new system, `feather-worldgen` doesn't seem to be updated yet:
https://github.com/feather-rs/feather/blob/0f6f217af81d753d7b697b80a8de206eb9cf5407/feather/worldgen/src/lib.rs#L324-L330

2021-04-19 14:18 UTC, michidk commented
Yeah, you are right. I thought of my changes as more of an improvement (the code that is broken is already in this repo, - now at least you can try out the world generation (without biomes)) than a rewrite for the whole generation system (which Iam not too familiar with either). Closing this for now.

2021-04-19 14:18 UTC, closed without merging