Fix Logging of Config
feather-rs/feather pull request #432
Opened 2021-06-07 19:16 UTC by FussballAndy

# Fix logging of Config

## Status

- [x] Ready 
- [ ] Development
- [ ] Hold

## Description

Fixed logging of config after my previous pr created a small "problem" with the config loading/creating not being logged.

## Checklist

- [x] Ran `cargo fmt`, `cargo clippy`, `cargo build --release` and `cargo test` and fixed any generated errors!
- [ ] Removed unnecessary commented out code
- [ ] Used specific traces (if you trace actions please specify the cause i.e. the player)

2021-06-07 22:14 UTC, amberkowalski approved these changes

2021-06-08 20:59 UTC, Defman requested changes

2021-06-08 20:59 UTC, Defman commented on feather/server/src/config.rs
> +pub fn load(path: &str) -> anyhow::Result<(Config, bool)> {
I think the result should be wrapped in a `struct`, since its not clear what the `bool` indicates.

2021-06-10 16:17 UTC, Defman approved these changes

2021-06-10 16:17 UTC, merged