Datapack parsing
feather-rs/feather pull request #455
Opened 2021-08-24 22:13 UTC by koskja

# Datapack parsing

## Status

- [ ] Ready 
- [x] Development
- [ ] Hold

## Description

The game needs to parse registries for most of its logic to function. This pull request attempts to do that.

## Related issues

#429

## Checklist

- [ ] Ran `cargo fmt`, `cargo clippy --all-targets`, `cargo build --release` and `cargo test` and fixed any generated errors!
- [ ] Removed unnecessary commented out code
- [ ] Used specific traces (if you trace actions please specify the cause i.e. the player)

Note: if you locally don't get any errors, but GitHub Actions fails (especially at `clippy`) you might want to check your rust toolchain version. You can then feel free to fix these warnings/errors in your PR.

2021-08-28 22:49 UTC, koskja commented
The functions now take `T: Into<NamespacedId> + Clone`. @caelunshun

2021-09-06 06:34 UTC, Defman requested changes
Looks good, the location of the generator.py is a bit odd and should be moved into the same directory with all other generators?

2021-09-06 06:34 UTC, Defman commented on feather/datapacks/tags.py
> +from os import listdir
Should be moved into the generator directory.

2021-09-06 17:57 UTC, koskja commented
Moved the tags generator. I believe the recipe implementation can be finished together with crafting.

2021-09-11 14:38 UTC, merged